### ISSUE TITLE
Text looks not well with guifont Iosevka

### ISSUE THREAD

**Issue by SilverRainZ** [smolck/uivonim#110]
I use [Iosevka](https://github.com/be5invis/Iosevka) as my code font, It seems that uivonim can not render it welcl, I am not sure who cause this problem.

![2021-01-29_13:49:23](https://user-images.githubusercontent.com/8090459/106237132-1763b380-6239-11eb-91fe-ae45c9642c6f.png)

**Comment by smolck** [comment]
Hmm, I'm not experiencing this issue with Iosevka installed. Text tends to look like that when the value set for `guifont` can't actually be found (and so it uses some default, and probably not monospaced, font), so are you sure you have `Iosevka` installed and not `Iosevka Term` or similar? In that case, doing `set guifont=Iosevka\ Term` should fix the issue (you have to pass the full name of the font).

**Comment by SilverRainZ** [comment]
It seems that I use a wrong syntax for guifonts:

```diff 
-set guifont=Iosevka\ 14
+set guifont=Iosevka:h16
```

Now it works well (but still something wrong when displaying chinese), should I open another issue to report it?

**Comment by smolck** [comment]
> It seems that I use a wrong syntax for guifonts:
> 
> ```diff
> -set guifont=Iosevka\ 14
> +set guifont=Iosevka:h16
> ```
> 
> Now it works well

Great! I'll go ahead and close this then.

> (but still something wrong when displaying chinese), should I open another issue to report it?

I have a feeling you're seeing a similar issue/the same issue as that of #107 (non-Latin text not rendering properly), just with Chinese instead of Devanagari, so you may wish to check that issue out and posting there before creating a new one. But I also don't mind a new issue if you'd prefer that or if yours is a different issue from that of #107.
