### ISSUE TITLE
Sometimes rendering is gone

### ISSUE THREAD

**Issue by trusktr** [smolck/uivonim#195]
I think after my screen turns off, and I come back to my laptop, all the rendering is gone. I mean, the editor area is blank. I still see the custom UI stuff on the bottom and top edges though, just nothing happens in the middle.

Have you experienced this?

**Comment by smolck** [comment]
Hmm . . . that is weird 😅 I have not experienced this; thanks for the opening the issue!

A few questions: what operating system are you on, can you reproduce this reliably, and if so how (e.g. can it be reproduced by putting your computer to sleep manually while the editor is open)?

**Comment by smolck** [comment]
Was able to reproduce by changing the scaling for my display in macOS (also could be reproduced by plugging in/unplugging an external monitor) to a different scaling. AFAIK the problem was the WebGL context(s) being lost in such cases (or in other cases, like the ones you experienced), and then not being restored afterwards.

Feel free to re-open if the issue persists.
