### ISSUE TITLE
Implement dead keys on Linux (and Windows?)

### ISSUE THREAD

**Issue by clason** [smolck/uivonim#8]
Dead keys are keys that emit special modifier events that can modify certain (but not all) subsequent keys. For example, on a German keyboard layout, these are `´`, backtick, `^`, and `~`, and entering `´` followed by `a` outputs `á` (while a second `´` or a space outputs a literal `´`).

These keys currently don't work in the main text entry (either for composition, literal output, or as normal mode mappings). They do work in the external command line, though (which uses system input).

**Comment by smolck** [comment]
So my guess is this will require a change in [`src/core/input.ts`](https://github.com/smolck/uivonim/blob/master/src/core/input.ts), but I’m not sure exactly what that change is. Here are two questions I have:

* How to know if a dead key is pressed? Isn’t that layout-specific?
* Okay, so now we know a dead key is pressed; what then? Set a flag and wait for the next key to determine the input to Neovim?

Also, I can’t really test this myself I don’t think (I use US standard layout), so that’ll make implementing this a bit more difficult.

**Comment by clason** [comment]
> * How to know if a dead key is pressed? Isn’t that layout-specific?

Yes, and also OS specific (just like the modifiers).

> * Okay, so now we know a dead key is pressed; what then? Set a flag and wait for the next key to determine the input to Neovim?

I think that is correct, yes.

> Also, I can’t really test this myself I don’t think (I use US standard layout), so that’ll make implementing this a bit more difficult.

The [US International layout](https://en.wikipedia.org/wiki/QWERTY#US-International) has dead keys.

**Comment by clason** [comment]
Maybe https://github.com/RobertWHurst/KeyboardJS can help?

**Comment by clason** [comment]
Seems like we need to handle not just `KeyboardEvents` but also `CompositionEvents`:
* https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event
* https://www.w3.org/TR/uievents/#keys-dead

**Comment by clason** [comment]
Unfortunately, this only works on the first buffer on startup -- loading a new buffer with `:e <filename>` or `:new` prevents dead keys from showing up again.

**Comment by clason** [comment]
Fixed (for now) in https://github.com/smolck/uivonim/commit/4ac68a12f46046959b3e7938ede6410f99f6e2b0.

**Comment by smolck** [comment]
Only works on MacOS, and I don't really know why. Seems like a problem with Chromium, in which case working around it could require implementing dead keys in a more manual way, i.e. seeing if the previous key was a dead key and then depending on the next key typed send a different character to neovim . . . which is not ideal.

I could be wrong, but I'm not sure what else could cause `keydown` events to return the proper characters on MacOS but not on Linux when using a dead key in the key sequence? The same issue doesn't happen on Firefox, so that's another reason to believe it's an issue with Chromium.
